config/routes.rb
Rails.application.routes.draw do
  resources :events do
    post :store_filter, on: :collection
    get :use_stored_filter, on: :collection
  end
  devise_for :users
  root to: 'events#index'
end

app/models/event_notification.rb
class EventNotification < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  validates :user, presence: true, uniqueness: {scope: :event_id}
  validates :event, presence: true
  scope :not_sent, ->{ where(sent_at: nil) }
  scope :created_before, ->time{
    where(arel_table[:created_at].lt(time))
  }

  def mark_as_read
    self.is_read = true
    save
  end

  def mark_as_unread
    self.is_read = false
    save
  end

  def mark_as_sent
    self.sent_at = Time.zone.now
    save
  end

  def mark_as_sent!
    self.sent_at = Time.zone.now
    save!
  end

  def sent?
    !!sent_at
  end

  def read?
    is_read
  end

  def unread?
    !is_read
  end
end

app/controllers/event_notifications_controller.rb
class EventNotificationsController < WebsocketRails::BaseController
  before_action :authenticate_user!

  def index
    # TODO: pagination
    begin
      event_notifications = current_user.event_notifications.includes(:event)

      html = ''.html_safe
      event_notifications.each do |event_notification|
        html << render_to_string(
          template: 'event_notifications/new',
          layout: false,
          assigns: {event_notification: event_notification, event: event_notification.event})
      end

      send_message :index_success, {html: html, count: event_notifications.count}, namespace: :event_notifications
    rescue => e
      send_message :index_error, {error: e.to_s}, namespace: :event_notifications
    end
  end

  def mark_as_read
    @event_notification = current_user.event_notifications.find_by(id: message[:id])
    if @event_notification && @event_notification.mark_as_read
      send_message :mark_as_read_success, {id: @event_notification.id}, namespace: :event_notifications
    else
      send_message :mark_as_read_error, {id: @event_notification.id}, namespace: :event_notifications
    end
  end

  def mark_as_unread
    @event_notification = current_user.event_notifications.find_by(id: message[:id])
    if @event_notification && @event_notification.mark_as_unread
      send_message :mark_as_unread_success, {id: @event_notification.id}, namespace: :event_notifications
    else
      send_message :mark_as_unread_error, {id: @event_notification.id}, namespace: :event_notifications
    end
  end

  def destroy
    @event_notification = current_user.event_notifications.find_by(id: message[:id])
    if @event_notification && @event_notification.destroy
      send_message :destroy_success, {id: @event_notification.id}, namespace: :event_notifications
    else
      send_message :destroy_error, {}, namespace: :event_notifications
    end
  end
end

app/views/event_notifications/new.html.erb
<div class="notification notification-<%= @event_notification.read? ? :read : :unread %>" id="event-notification-<%= @event_notification.id %>" data-id="<%= @event_notification.id %>" >
  <div>
   There is a new event <%= link_to @event.title, event_path(@event) %> matching your stored event filter.
  </div>
  <div>
    <%= link_to 'Delete', 'javascript:void(0)', class: 'js-delete-notification' %>
    <% if @event_notification.read? %>
      <%= link_to 'Mark as unread', 'javascript:void(0)', class: 'js-mark-as-unread-notification' %>
    <% else %>
      <%= link_to 'Mark as read', 'javascript:void(0)', class: 'js-mark-as-read-notification' %>
    <% end %>
  </div>
</div>