config/routes.rb
Rails.application.routes.draw do
  resources :events do
    post :store_filter, on: :collection
    get :use_stored_filter, on: :collection
  end
  devise_for :users
  root to: 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  validates :title, presence: true
  validates :user, presence: true
  validates :city_id, presence: true
  validates :city, presence: true
  validates :start_at, presence: true
  validates :finish_at, presence: true
  validates :description, presence: true
  validate :range_validator

  has_and_belongs_to_many :themes
  has_many :event_notifications, dependent: :destroy

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    # Пока только по created_at
    order(arel_table[:created_at].send(direction))
  }

  scope :with_theme_id, ->theme_id{
    joins(:themes).where(themes: {id: theme_id})
  }

  scope :with_start_at_between, ->range_attrs{
    from = convert_to_time(range_attrs[:from])
    to = convert_to_time(range_attrs[:to])
    next unless from && to
    if from > to
      none
    else
      where(arel_table[:start_at].between(from..to))
    end
  }

  scope :with_city_id, ->city_id{ where(city_id: city_id) }

  filterrific default_filter_params: {sorted_by: 'created_at_desc'},
    available_filters: [
      :sorted_by,
      :with_theme_id,
      :with_start_at_between,
      :with_city_id,
    ]

  def self.options_for_city_id
    City.all
  end

  def self.convert_to_time(value)
    if value.is_a?(Time)
      value
    elsif value.is_a?(String)
      Time.zone.parse(value) rescue nil
    else
      nil
    end
  end

  private

    def range_validator
      errors.add(:start_at, :more_than_start) if start_at && finish_at && start_at >= finish_at
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @filterrific = initialize_filterrific(
      Event,
      filter_params,
      select_options: {
        with_city_id: City.all,
        with_theme_id: Theme.all,
      }
    ) or return
    @events = @filterrific.find.includes(:city, :user, :themes).page(params[:page]).per_page(10)
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def store_filter
    @event_filter = current_user.event_filter
    @event_filter.clear_filter_attributes
    @event_filter.attributes = filter_params
    @event_filter.save
    respond_to do |format|
      format.json {}
    end
  end

  def use_stored_filter
    @event_filter = current_user.event_filter
    redirect_to action: :index, event_filter: @event_filter.to_filterrific_params
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    respond_to do |format|
      if @event.save
        NewEventJob.perform_later(@event)
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        NewEventJob.perform_later(@event)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def event_params
      params.require(:event).permit(:title, :description, :city_id, :start_at, :finish_at, theme_ids: [])
    end

    def filter_params
      params.require(:event_filter).permit(
        :reset_filterrific,
        :with_city_id, :with_theme_id, with_start_at_between: [:from, :to]) if params[:event_filter]
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_list.html.erb
<% count = 0 %>
<% @events.each do |event| %>
  <% count += 1 %>
  <div class="event-item">
    <h3><%= if can?(:show, event)
      link_to event.title, event
    else
      event.title
    end %></h3>
    <% themes = event.themes.map(&:name).join(', ') %>
    <% if themes.present? %>
      <div>
        Themes: <%= themes %>
      </div>
    <% end %>
    <div>
      User: <%= event.user.email %>
    </div>
    <div>
      City: <%= event.city.name %>
    </div>
    <div>
      Dates: <%= l event.start_at %> &mdash; <%= l event.finish_at %>
    </div>
  </div>
<% end %>
<% if count == 0 %>
<i>No events published yet</i>
<% end %>

app/views/events/_filter.html.erb
<%= link_to 'Use stored filter', use_stored_filter_events_path if can?(:use_stored_filter, Event) %>
<%= simple_form_for_filterrific @filterrific, defaults: {required: false}, as: :event_filter do |form| %>
  <%= form.input :with_city_id, as: :select, collection: @filterrific.select_options[:with_city_id] %>

  <%= form.input :with_theme_id, label: false, as: :radio_buttons do %>
    <%= form.label :with_theme_id, required: false %>
    <%= link_to 'reset', 'javascript:void(0)', class: 'js-reset-event-filter-theme' %>
    <%= form.input :with_theme_id, wrapper: false, error: false, label: false, as: :radio_buttons, collection: @filterrific.select_options[:with_theme_id] %>
  <% end %>

  <%= form.fields_for :with_start_at_between, OpenStruct.new(@filterrific.with_start_at_between), defaults: {required: false} do |f| %>
    <%= f.input :from, as: :string do %>
      <%= bootstrap_datetime_picker(f, :from) %>
    <% end %>
    <%= f.input :to, as: :string do %>
      <%= bootstrap_datetime_picker(f, :to) %>
    <% end %>
  <% end %>
  <%= render_filterrific_spinner %>

  <div>
    <%= link_to('Reset filters', {event_filter: { reset_filterrific: true } }) %>
    <%= link_to('Store filter', 'javascript:void(0)', class: 'js-save-filter', data: {
        url: store_filter_events_path,
      }) if can?(:store_filter, Event) %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.input :title, as: :string %>
  <%= f.input :city_id, as: :select, collection: City.all %>
  <%= f.input :start_at, as: :string do %>
    <%= bootstrap_datetime_picker f, :start_at %>
  <% end %>
  <%= f.input :finish_at, as: :string do %>
    <%= bootstrap_datetime_picker f, :finish_at %>
  <% end %>
  <%= f.input :description %>
  <%= f.association :themes, collection: Theme.all, input_html: {class: 'js-theme-select'} %>
  <%= f.button :submit %>
<% end %>

app/views/events/_list.html.erb
<% count = 0 %>
<% events.each do |event| %>
  <% count += 1 %>
  <div class="event-item">
    <h3><%= if can?(:show, event)
      link_to event.title, event
    else
      event.title
    end %></h3>
    <% themes = event.themes.map(&:name).join(', ') %>
    <% if themes.present? %>
      <div>
        Themes: <%= themes %>
      </div>
    <% end %>
    <div>
      User: <%= event.user.email %>
    </div>
    <div>
      City: <%= event.city.name %>
    </div>
    <div>
      Dates: <%= l event.start_at %> &mdash; <%= l event.finish_at %>
    </div>
  </div>
<% end %>
<% if count == 0 %>
<i>No events here yet</i>
<% end %>

<%= will_paginate events, renderer: BootstrapPagination::Rails %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
<hr/>

<div class="col-sm-4">
  <%= render partial: 'filter' %>
</div>

<div class="col-sm-8">
  <%= link_to 'New event', new_event_path, class: 'btn btn-default' if can?(:new, Event) %>
  <div id="event-list">
    <%= render partial: 'list', locals: {events: @events} %>
  </div>
</div>

app/views/events/index.js.erb
<% js = escape_javascript(render(partial: 'events/list', locals: {events: @events})) %>
$('#event-list').html("<%= js %>")

app/views/events/new.html.erb
<div class="col-sm-4"></div>
<div class="col-sm-4">
  <h1>New Event</h1>
<%= render 'form' %>
<%= link_to 'Back', events_path %>
</div>
<div class="col-sm-4"></div>

app/views/events/show.html.erb
<h2><%= @event.title %>
  <% if can?(:edit, @event) %>
  <small><%= link_to 'Edit', edit_event_path(@event)  %></small>
  <% end %>
</h2>
<div>
  <strong>Themes:</strong> <%= @event.themes.map(&:name).join(', ') %>
</div>

<div>
  <strong>City:</strong> <%= @event.city.name %>
</div>

<div>
  <strong>Author:</strong> <%= @event.user.email %>
</div>

<div>
  <strong>Dates:</strong> <%= l @event.start_at %> &mdash; <%= l @event.finish_at %>
</div>

<p>
  <%= simple_format(@event.description) %>
</p>

<div class="button-group">
  
</div>